---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: cluster
  namespace: system-upgrade
spec:
  version: v1.22.1
  concurrency: 1
  cordon: false
  nodeSelector:
    matchExpressions:
      - {key: plan.upgrade.cattle.io/cluster, operator: Exists}
  upgrade:
    image: "ubuntu:bionic"
    command: ["chroot", "/host"]
    args:
      - /bin/sh
      - -c
      - |-
        apt-get update && \
        apt-get install -y --allow-change-held-packages \
          "kubeadm=${SYSTEM_UPGRADE_PLAN_LATEST_VERSION#v}-00" && \
        apt-mark hold kubeadm && \
        kubeadm upgrade plan "$SYSTEM_UPGRADE_PLAN_LATEST_VERSION" && \
        kubeadm upgrade apply --yes "$SYSTEM_UPGRADE_PLAN_LATEST_VERSION" && \
        KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply \
          -f https://docs.projectcalico.org/manifests/calico.yaml
