---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: kubelet
  namespace: system-upgrade
spec:
  # I don't use "channel" here so I can control myself when an upgrade is
  # applied
  version: v1.22.1
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - {key: kubernetes.io/os, operator: In, values: ["linux"]}
  serviceAccountName: system-upgrade
  drain:
    force: true
  secrets:
    - name: scripts
      path: /host/run/system-upgrade/scripts
  upgrade:
    image: "ubuntu:bionic"
    command: ["chroot", "/host"]
    args: ["bash", "/run/system-upgrade/scripts/upgrade-k8s.sh"]
