---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: kubelet
  namespace: system-upgrade
spec:
  version: v1.22.0
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - {key: kubernetes.io/os, operator: In, values: ["linux"]}
  serviceAccountName: system-upgrade
  drain:
    force: true
  upgrade:
    image: "ubuntu:bionic"
    command: ["chroot", "/host"]
    args:
      - /bin/sh
      - -c
      - |-
        set -e -x

        apt-get update
        apt-get install -y --allow-change-held-packages \
          "kubeadm=${SYSTEM_UPGRADE_PLAN_LATEST_VERSION#v}-00" \
          "kubelet=${SYSTEM_UPGRADE_PLAN_LATEST_VERSION#v}-00" \
          "kubectl=${SYSTEM_UPGRADE_PLAN_LATEST_VERSION#v}-00"
        apt-mark hold kubeadm kubelet kubectl

        kubeadm upgrade node

        kubelet_pid="$(pgrep kubelet)"
        systemctl daemon-reload
        systemctl restart kubelet

        echo -n "Waiting for kubelet to restart"
        while [[ "$(pgrep kubelet)" == "$kubelet_pid" ]]; do
          echo -n .
          sleep 1
        done

        while [[ "$(curl -sSk https://127.0.0.1:10250/healthz)" != "Unauthorizedd" ]]; do
          echo -n .
          sleep 1
        done
        echo
        echo "All done"
