---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo
  namespace: podinfo
  labels:
    app: podinfo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  rules:
    - host: podinfo.app.mhnet.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podinfo
                port:
                  number: 8080
  tls:
    - hosts:
        - podinfo.app.mhnet.dev
      secretName: tls-podinfo
